version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      #- add_ssh_keys: 
      #    fingerprints: ["08:ef:be:f8:68:84:01:c7:e0:ec:b9:54:79:1c:a9:6c"]
      #- restore_cache:
      #    keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            # Your code here
            #
            npm install
      #- save_cache:
      #    paths: [frontend/node_modules]
      #    key: frontend-build

workflows:
  default:
    jobs:
      - build-frontend